# Generated by Django 5.2.3 on 2025-07-19 17:08

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('improve_health', 'Improve Health'), ('maintain', 'Maintain Weight')], max_length=20),
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
